// Package schemas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/KosyanMedia/oapi-codegen/v2 version (devel) DO NOT EDIT.
package schemas

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/KosyanMedia/oapi-codegen/v2/pkg/runtime"
	"github.com/creasty/defaults"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for EnumInObjInArrayVal.
const (
	First  EnumInObjInArrayVal = "first"
	Second EnumInObjInArrayVal = "second"
)

// This schema name starts with a number
type N5StartsWithNumber = map[string]interface{}

// AnyType1 defines model for AnyType1.
type AnyType1 = interface{}

// AnyType2 represents any type.
//
// This should be an interface{}
type AnyType2 = interface{}

// CustomStringType defines model for CustomStringType.
type CustomStringType = string

// EnsuredefaultsnopointersJSONRequestBodySchema defines model for EnsuredefaultsnopointersJSONRequestBodySchema.
type EnsuredefaultsnopointersJSONRequestBodySchema struct {
	BoolField   bool    `default:"false" json:"bool_field,omitempty"`
	FloatField  float64 `default:"0" json:"float_field,omitempty"`
	IntField    int     `default:"0" json:"int_field,omitempty"`
	StringField string  `default:"" json:"string_field,omitempty"`
}

// Ensureeverythingisreferenced200JSONResponseBodySchema defines model for Ensureeverythingisreferenced200JSONResponseBodySchema.
type Ensureeverythingisreferenced200JSONResponseBodySchema struct {
	AnyType1 AnyType1 `json:"anyType1,omitempty"`

	// AnyType2 represents any type.
	//
	// This should be an interface{}
	AnyType2         AnyType2          `json:"anyType2,omitempty"`
	CustomStringType *CustomStringType `foo:"bar" json:"customStringType,omitempty"`
}

// EnumInObjInArray defines model for EnumInObjInArray.
type EnumInObjInArray = []struct {
	Val *EnumInObjInArrayVal `json:"val,omitempty" validate:"omitempty,oneof=first second"`
}

// EnumInObjInArrayVal defines model for EnumInObjInArray.Val.
type EnumInObjInArrayVal string

// GenericObject defines model for GenericObject.
type GenericObject = map[string]interface{}

// NullableProperties defines model for NullableProperties.
type NullableProperties struct {
	Optional            *string `json:"optional,omitempty"`
	OptionalAndNullable *string `json:"optionalAndNullable,omitempty"`
	Required            string  `json:"required" validate:"required"`
	RequiredAndNullable *string `json:"requiredAndNullable" validate:"required"`
}

// StringInPath defines model for StringInPath.
type StringInPath = string

// EnsureDefaultsNoPointersJSONBody defines parameters for EnsureDefaultsNoPointers.
type EnsureDefaultsNoPointersJSONBody = EnsuredefaultsnopointersJSONRequestBodySchema

// Issue185JSONBody defines parameters for Issue185.
type Issue185JSONBody = NullableProperties

// Issue9JSONBody defines parameters for Issue9.
type Issue9JSONBody = interface{}

// Issue9Params defines parameters for Issue9.
type Issue9Params struct {
	Foo string `form:"foo" json:"foo" validate:"required"`
}

// EnsureDefaultsNoPointersJSONRequestBody defines body for EnsureDefaultsNoPointers for application/json ContentType.
type EnsureDefaultsNoPointersJSONRequestBody = EnsureDefaultsNoPointersJSONBody

// Issue185JSONRequestBody defines body for Issue185 for application/json ContentType.
type Issue185JSONRequestBody = Issue185JSONBody

// Issue9JSONRequestBody defines body for Issue9 for application/json ContentType.
type Issue9JSONRequestBody = Issue9JSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /ensure-defaults-no-pointers)
	EnsureDefaultsNoPointers(ctx echo.Context, requestBody EnsureDefaultsNoPointersJSONBody) (code int, err error)

	// (GET /ensure-everything-is-referenced)
	EnsureEverythingIsReferenced(ctx echo.Context) (resp *EnsureEverythingIsReferencedResponse, err error)

	// (GET /issues/127)
	Issue127(ctx echo.Context) (resp *Issue127Response, err error)

	// (GET /issues/185)
	Issue185(ctx echo.Context, requestBody Issue185JSONBody) (code int, err error)

	// (GET /issues/209/${str})
	Issue209(ctx echo.Context, str StringInPath) (code int, err error)

	// (GET /issues/30/{fallthrough})
	Issue30(ctx echo.Context, pFallthrough string) (code int, err error)

	// (GET /issues/375)
	GetIssues375(ctx echo.Context) (resp *GetIssues375Response, err error)

	// (GET /issues/41/{1param})
	Issue41(ctx echo.Context, n1param N5StartsWithNumber) (code int, err error)

	// (GET /issues/9)
	Issue9(ctx echo.Context, params Issue9Params, requestBody Issue9JSONBody) (code int, err error)
}

type EnsureEverythingIsReferencedResponse struct {
	Code    int
	JSON200 *Ensureeverythingisreferenced200JSONResponseBodySchema
}

type Issue127Response struct {
	Code        int
	JSON200     GenericObject
	XML200      GenericObject
	YAML200     GenericObject
	JSONDefault GenericObject
}

type GetIssues375Response struct {
	Code    int
	JSON200 EnumInObjInArray
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// EnsureDefaultsNoPointers converts echo context to params.
func (w *ServerInterfaceWrapper) EnsureDefaultsNoPointers(ctx echo.Context) error {
	var err error

	var requestBody EnsureDefaultsNoPointersJSONBody
	err = ctx.Bind(&requestBody)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Failed to parse request body: %s", err))
	}
	if err = defaults.Set(&requestBody); err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, fmt.Sprintf("Failed to set defaults to request body: %s", err))
	}

	if err = runtime.ValidateInput(requestBody); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.EnsureDefaultsNoPointers(ctx, requestBody)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// EnsureEverythingIsReferenced converts echo context to params.
func (w *ServerInterfaceWrapper) EnsureEverythingIsReferenced(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.EnsureEverythingIsReferenced(ctx)

	if err != nil {
		return err
	}

	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	return ctx.NoContent(response.Code)
}

// Issue127 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue127(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue127(ctx)

	if err != nil {
		return err
	}

	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	if response.JSONDefault != nil {
		return ctx.JSON(response.Code, response.JSONDefault)
	}
	return ctx.NoContent(response.Code)
}

// Issue185 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue185(ctx echo.Context) error {
	var err error

	var requestBody Issue185JSONBody
	err = ctx.Bind(&requestBody)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Failed to parse request body: %s", err))
	}

	if err = runtime.ValidateInput(requestBody); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue185(ctx, requestBody)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// Issue209 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue209(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "str" -------------
	var str StringInPath

	err = runtime.BindStyledParameterWithLocation("simple", false, "str", runtime.ParamLocationPath, ctx.Param("str"), &str)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter str: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue209(ctx, str)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// Issue30 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue30(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fallthrough" -------------
	var pFallthrough string

	err = runtime.BindStyledParameterWithLocation("simple", false, "fallthrough", runtime.ParamLocationPath, ctx.Param("fallthrough"), &pFallthrough)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fallthrough: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue30(ctx, pFallthrough)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// GetIssues375 converts echo context to params.
func (w *ServerInterfaceWrapper) GetIssues375(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.GetIssues375(ctx)

	if err != nil {
		return err
	}

	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	return ctx.NoContent(response.Code)
}

// Issue41 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue41(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "1param" -------------
	var n1param N5StartsWithNumber

	err = runtime.BindStyledParameterWithLocation("simple", false, "1param", runtime.ParamLocationPath, ctx.Param("1param"), &n1param)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter 1param: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue41(ctx, n1param)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// Issue9 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue9(ctx echo.Context) error {
	var err error

	var requestBody Issue9JSONBody
	err = ctx.Bind(&requestBody)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Failed to parse request body: %s", err))
	}

	if err = runtime.ValidateInput(requestBody); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params Issue9Params
	// ------------- Required query parameter "foo" -------------

	err = runtime.BindQueryParameter("form", true, true, "foo", ctx.QueryParams(), &params.Foo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter foo: %s", err))
	}

	if err = runtime.ValidateInput(params); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue9(ctx, params, requestBody)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface, m ...echo.MiddlewareFunc) {
	RegisterHandlersWithBaseURL(router, si, "", m...)
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string, m ...echo.MiddlewareFunc) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/ensure-defaults-no-pointers", wrapper.EnsureDefaultsNoPointers, m...)
	router.GET(baseURL+"/ensure-everything-is-referenced", wrapper.EnsureEverythingIsReferenced, m...)
	router.GET(baseURL+"/issues/127", wrapper.Issue127, m...)
	router.GET(baseURL+"/issues/185", wrapper.Issue185, m...)
	router.GET(baseURL+"/issues/209/$:str", wrapper.Issue209, m...)
	router.GET(baseURL+"/issues/30/:fallthrough", wrapper.Issue30, m...)
	router.GET(baseURL+"/issues/375", wrapper.GetIssues375, m...)
	router.GET(baseURL+"/issues/41/:1param", wrapper.Issue41, m...)
	router.GET(baseURL+"/issues/9", wrapper.Issue9, m...)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXUW/bOAz+K4JuwL04cZpt2Jq33m43dIdri7XAHprioFh0rNWmPEluawT+7wdKdpws",
	"dm+9rcD1pUlEUuQn8iO54YkuSo2AzvLFhpfCiAIcGP/t0hmF61O8EC6j7xJsYlTplEa+4CfM+nNWCpex",
	"rSaPuKJj+pVHHEUBfMGtowMDXytlQPKFMxVE3CYZFIJMu7psxRSuedM03aF35PWlE8bZz8plZ1WxAnPo",
	"zVWmLAsqjO5k1quwe+UyJhgGtai7SK++QOJ4E/ETrK/qEo74YtN/mw+E254wA6UBS4gxgTUjg9MlLjF4",
	"kOkql2wFTCBT6MCkIoFNs0S6611lnS4CrFfekQ1PtSmE4wue+MPexRaLiD9MtCjVJNES1oATeHBGTJxY",
	"26Cu+YKvhOGE2Xu0lQEJqahyZ1GX2vtgP16en32CrxVY95uW9eUW99LoEoxT4I2ttM7/ThXkMsTvzfBF",
	"KnILW79ICISPJ821cAMKs6gPS+pqlUMfVvsSDaXJiG4rSa6vg2jAYkCaH+BFMBw8csAF7sDULlO4VtZA",
	"CgYwATmfzQI8ttRo4TF8RJ8r/IWBlC/4L3FfQXGbsvE2p5qo05l/p86cdJKBPHlM9yCvRkCoilM8X305",
	"xRNjRE1WlYPCHgZ6J3L6B1gVfHHNU2Ws4xG3kGiU/Oa7MG9/EP6qJuIfAMGo5DwI9DXfa5xVeS5WOVzs",
	"+bLvmfb1GNz7xoloe3iCsrNFcrj9HGjnQK/npc344dOM7lm97j8P27s5wK/xaFdGuZCNbQImCVg7cfoW",
	"0BcsCAPmj67WPn6+moTCY0GSecnpEnnLp76AvVJfOJlzZaBchakeoFawjiXCgmWpNuxOGKUry5S1lf+p",
	"Qsn0HRjmVAFTdpGDsMCElEww1+mS6hKJMFfVmqXqAWRwyylHIIZbLsHcedfuwNhw+9F0Np2FxwUUpeIL",
	"/nI6mx7xyLcYD0sMvr4nHfFNUE866qPzNbiRjgEovSCDB2WdZVYzlwnH+iJjiUDi88SAcCCZQuYyZZdo",
	"S0iYQMlQOxIoTYUgfUyUsIKuOZV80ZLP761vZ/qi8yzkQsvJ5GCi0QF6X0VZ5irxRuIvVvvX7tvlY2Tw",
	"tB7QNCFVA/l5tOaz2SFa53+2oh3WPZlOlJ30dPp/wfv91r9T+6n3bjjWnwj8U5tME/4iHoeCio/mb0Yx",
	"/EvcAqNbWIW2KkttCCLv/YPzo4hlUuOvjpUGoCgd66X86XQAr1O6l259Rmz2yZ/C3bX1UOQ/YoqCjwth",
	"bqW+xx82VIsf8YbMbKeTZwPvJ0X8bea9fT1evXUJbE36PgJ2nwGyrt/GXU9jfbNmwgDrmuR42r19/Uw0",
	"ODBMHHAdubcLwHx2HL/YWGeaURzeZZDcWqbSfuMJoUpIctFDkNfDAc9nx/zQh2hv87oejqwXifc2s+Zm",
	"J4SXs3iTijx3mdHVOmsOI/gElrqsZLdQ32sjd5eW0oBvzcS61OcJQL9OtcTRQjIQ18vZ94Q1sBnuOPuk",
	"DXEv6DfjiUtTb/s4beYK2yUyseK9SoCe02XAaN715wppfwuz2BLvM5Vk7e9WSWA6pWM/2Q5l9gdwHhNL",
	"fj1rw/lmoD+o6FdH8ebIv8F4Rl90T7SzN9Na7zfn7d488OSvwgz2bw8c7n/0bR8L8nD3b5qbR6v4eLx4",
	"cwXoQuVa3xCZwkQbA4nLa/qcVxKkH3NbTgowrLSsafZYYh/vKKcdj8DytQJT7yS+1k9L+P/Mk21T2hvn",
	"Wub2kfEhVtxZQHwI+6vH9Q3544mkDbEyebtLLOK4ndVp+p9KgLIQ5VQoYqp/AgAA//+xvUZDchIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
