// Package schemas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/KosyanMedia/oapi-codegen/v2 version (devel) DO NOT EDIT.
package schemas

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/KosyanMedia/oapi-codegen/v2/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for EnumInObjInArrayVal.
const (
	First  EnumInObjInArrayVal = "first"
	Second EnumInObjInArrayVal = "second"
)

// This schema name starts with a number
type N5StartsWithNumber = map[string]interface{}

// AnyType1 defines model for AnyType1.
type AnyType1 = interface{}

// AnyType2 represents any type.
//
// This should be an interface{}
type AnyType2 = interface{}

// CustomStringType defines model for CustomStringType.
type CustomStringType = string

// Ensureeverythingisreferenced200JSONResponseBodySchema defines model for Ensureeverythingisreferenced200JSONResponseBodySchema.
type Ensureeverythingisreferenced200JSONResponseBodySchema struct {
	AnyType1 AnyType1 `json:"anyType1,omitempty"`

	// AnyType2 represents any type.
	//
	// This should be an interface{}
	AnyType2         AnyType2          `json:"anyType2,omitempty"`
	CustomStringType *CustomStringType `foo:"bar" json:"customStringType,omitempty"`
}

// EnumInObjInArray defines model for EnumInObjInArray.
type EnumInObjInArray = []struct {
	Val *EnumInObjInArrayVal `json:"val,omitempty" validate:"omitempty,oneof=first second"`
}

// EnumInObjInArrayVal defines model for EnumInObjInArray.Val.
type EnumInObjInArrayVal string

// GenericObject defines model for GenericObject.
type GenericObject = map[string]interface{}

// NullableProperties defines model for NullableProperties.
type NullableProperties struct {
	Optional            *string `json:"optional,omitempty"`
	OptionalAndNullable *string `json:"optionalAndNullable,omitempty"`
	Required            string  `json:"required" validate:"required"`
	RequiredAndNullable *string `json:"requiredAndNullable" validate:"required"`
}

// StringInPath defines model for StringInPath.
type StringInPath = string

// Issue185JSONBody defines parameters for Issue185.
type Issue185JSONBody = NullableProperties

// Issue9JSONBody defines parameters for Issue9.
type Issue9JSONBody = interface{}

// Issue9Params defines parameters for Issue9.
type Issue9Params struct {
	Foo string `form:"foo" json:"foo" validate:"required"`
}

// Issue185JSONRequestBody defines body for Issue185 for application/json ContentType.
type Issue185JSONRequestBody = Issue185JSONBody

// Issue9JSONRequestBody defines body for Issue9 for application/json ContentType.
type Issue9JSONRequestBody = Issue9JSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /ensure-everything-is-referenced)
	EnsureEverythingIsReferenced(ctx echo.Context) (resp *EnsureEverythingIsReferencedResponse, err error)

	// (GET /issues/127)
	Issue127(ctx echo.Context) (resp *Issue127Response, err error)

	// (GET /issues/185)
	Issue185(ctx echo.Context, requestBody Issue185JSONBody) (code int, err error)

	// (GET /issues/209/${str})
	Issue209(ctx echo.Context, str StringInPath) (code int, err error)

	// (GET /issues/30/{fallthrough})
	Issue30(ctx echo.Context, pFallthrough string) (code int, err error)

	// (GET /issues/375)
	GetIssues375(ctx echo.Context) (resp *GetIssues375Response, err error)

	// (GET /issues/41/{1param})
	Issue41(ctx echo.Context, n1param N5StartsWithNumber) (code int, err error)

	// (GET /issues/9)
	Issue9(ctx echo.Context, params Issue9Params, requestBody Issue9JSONBody) (code int, err error)
}

type EnsureEverythingIsReferencedResponse struct {
	Code    int
	JSON200 *Ensureeverythingisreferenced200JSONResponseBodySchema
}

type Issue127Response struct {
	Code        int
	JSON200     GenericObject
	XML200      GenericObject
	YAML200     GenericObject
	JSONDefault GenericObject
}

type GetIssues375Response struct {
	Code    int
	JSON200 EnumInObjInArray
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// EnsureEverythingIsReferenced converts echo context to params.
func (w *ServerInterfaceWrapper) EnsureEverythingIsReferenced(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.EnsureEverythingIsReferenced(ctx)

	if err != nil {
		return err
	}

	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	return ctx.NoContent(response.Code)
}

// Issue127 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue127(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue127(ctx)

	if err != nil {
		return err
	}

	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	if response.JSONDefault != nil {
		return ctx.JSON(response.Code, response.JSONDefault)
	}
	return ctx.NoContent(response.Code)
}

// Issue185 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue185(ctx echo.Context) error {
	var err error

	var requestBody Issue185JSONBody
	err = ctx.Bind(&requestBody)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Failed to parse request body: %s", err))
	}

	if err = runtime.ValidateInput(requestBody); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue185(ctx, requestBody)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// Issue209 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue209(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "str" -------------
	var str StringInPath

	err = runtime.BindStyledParameterWithLocation("simple", false, "str", runtime.ParamLocationPath, ctx.Param("str"), &str)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter str: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue209(ctx, str)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// Issue30 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue30(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "fallthrough" -------------
	var pFallthrough string

	err = runtime.BindStyledParameterWithLocation("simple", false, "fallthrough", runtime.ParamLocationPath, ctx.Param("fallthrough"), &pFallthrough)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter fallthrough: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue30(ctx, pFallthrough)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// GetIssues375 converts echo context to params.
func (w *ServerInterfaceWrapper) GetIssues375(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.GetIssues375(ctx)

	if err != nil {
		return err
	}

	if response.JSON200 != nil {
		if response.Code == 0 {
			response.Code = 200
		}
		return ctx.JSON(response.Code, response.JSON200)
	}
	return ctx.NoContent(response.Code)
}

// Issue41 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue41(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "1param" -------------
	var n1param N5StartsWithNumber

	err = runtime.BindStyledParameterWithLocation("simple", false, "1param", runtime.ParamLocationPath, ctx.Param("1param"), &n1param)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter 1param: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue41(ctx, n1param)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// Issue9 converts echo context to params.
func (w *ServerInterfaceWrapper) Issue9(ctx echo.Context) error {
	var err error

	var requestBody Issue9JSONBody
	err = ctx.Bind(&requestBody)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Failed to parse request body: %s", err))
	}

	if err = runtime.ValidateInput(requestBody); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params Issue9Params
	// ------------- Required query parameter "foo" -------------

	err = runtime.BindQueryParameter("form", true, true, "foo", ctx.QueryParams(), &params.Foo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter foo: %s", err))
	}

	if err = runtime.ValidateInput(params); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}

	// Invoke the callback with all the unmarshalled arguments
	response, err := w.Handler.Issue9(ctx, params, requestBody)

	if err != nil {
		return err
	}

	return ctx.NoContent(response)
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface, m ...echo.MiddlewareFunc) {
	RegisterHandlersWithBaseURL(router, si, "", m...)
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string, m ...echo.MiddlewareFunc) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/ensure-everything-is-referenced", wrapper.EnsureEverythingIsReferenced, m...)
	router.GET(baseURL+"/issues/127", wrapper.Issue127, m...)
	router.GET(baseURL+"/issues/185", wrapper.Issue185, m...)
	router.GET(baseURL+"/issues/209/$:str", wrapper.Issue209, m...)
	router.GET(baseURL+"/issues/30/:fallthrough", wrapper.Issue30, m...)
	router.GET(baseURL+"/issues/375", wrapper.GetIssues375, m...)
	router.GET(baseURL+"/issues/41/:1param", wrapper.Issue41, m...)
	router.GET(baseURL+"/issues/9", wrapper.Issue9, m...)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RXTW/bOBP+KwO+Bd6LbDluiza+ZYtukQLbBE2AHuIcaHFssZGGKkklEQz998WQsmXX",
	"crZfySWWyPl4Hs48HK1FZsrKEJJ3YrYWlbSyRI82PF15q2l1TpfS5/ys0GVWV14bEjNxBi6sQyV9DltL",
	"kQjNy/xWJIJkiWImnOcFi99qbVGJmbc1JsJlOZaSXfum6rZpWom2bTeLIZHXV15a775on3+qywXaw2yu",
	"c+0gmgDHBBdM4EH7HCRQNEs2gcziK2ZetIk4o+a6qfBEzNb903QAbrcCFiuLjhkDSQ2ww/Gc5hQzyE1d",
	"KFggSAJNHu1SZrhu58Sx3tXOmzLSeh0SWYulsaX0YiaysNin2HGRiMeRkZUeZUbhCmmEj97KkZcrF82N",
	"mImFtII5e0+utoj3aBufa1ppZ3GJFilDNZ1MPl5dfPqMrjLk8C+jmqst/5U1FVqvMTiVPSfihcWlmIn/",
	"pX2lpN3RpFvu2mRjM/1BmynbZAN8PGV7wB9jPjjR91SX53Sx+HpOZ9bKhr1qj6U7BHovC/6HVJdidiOW",
	"2jovEuEwM6TEbXJQlwPhuhcyhGoT8QEJrc4u4oa+tnuLT3VRyEWBl3u57GdmQt3F9L5LItkunpHa+OJ9",
	"tP0d2+vAru+/9fHFn3O65/Wm/z3s7/aAvzawXVvtYzV2BZhl6NzImzskfl6gtGj/3rTKxy/Xo9g3EHdC",
	"2Dmek+h0g0NEo76hcu+rKC2almZAQtB5yKRDB0tj4V5abWoH2rk6vKpJgblHC16XOIbLAqVDkEqBBL+x",
	"ZdM5sTAs6hUs9SOqmJbXnkmMUa7Q3ofU7tG6GP1kPBlP4uEiyUqLmXg5noxPRBKkNNCSYujvUd/gI+1G",
	"fYvznhX6I+qIpCqjyQM+aucdOAM+lx76RoNMEmtXZlF6VKAJfK7dnFyFGUhSQMbzhsrWhCrg4qKVHOZc",
	"iVknQO+3+Z27z312XBNRfAKa6WTC/zJDHikkLauq0Fnwln51Jhx9f0c8pQy/Jnxt/EtEGg85PZm+Ocrh",
	"P/IOgaNATa6uKmOZopD9ow/XgANl6P8eKotYVh76XWF1PMDXOcflqM/Izb4gMdxdX49l8TuuGHxaSnun",
	"zAP9tqNG/k427EbhUtaFf0by/hDi7yvv7evj3dtUCCu2DwjgIUeCzR2QbnQW+gsEpEXYCPfxsnv7upNp",
	"dJ674o+RNnDBRbQ7Nc7p7RIwnZymL9bO2/YoD+9yzO4c6GU/bUaoCrNC9hQUzTDg6eRUHOaQ7E29N8PI",
	"+i3p3lTc3u5AeDlJ10tZFD63pl7l7SGCz+hY+RXcYfNgrNodGCuL4bpg1eW7hwkMo2wnHB0lA7heTn4E",
	"1sBUvpPsT03ne6DfHC9cnsS6w+kqV7pNIbMqPugM+Th9jsAzWFjXxLNznA/m9JDrLO/eO60QzJKXw7Q1",
	"VNkf0AdOHOf1rBfOd0PmQUe/OknXJ+EMjlf05eaIdr5Z+JMqfLVsv1kGjvxVnAv+64Bj/CfP9imQh99d",
	"bXv7ZBefHm/eQiP52LkuXIigKTPWYuaLhn8XtUIVRq9OkyINC6Manj3m1OM9qmmnR2j5VqNtdgrfmJ8r",
	"+F/Wye5S2mXiolPugEwMqeLOUBwg7I/DN7ecTxCSDmJti26+naVpNz/yRDpWiFUpq7HUrFT/BgAA///7",
	"3Tue7g8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
