name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches: [ master ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16

    - name: Update apt
      run: sudo apt update

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Run tests
      run: make test

